namespace GeneratedEndpoints.Common;

internal static partial class Constants
{
    private const string GeneratorName = "GeneratedEndpoints.MinimalApiGenerator";
    private static string GeneratorVersion => typeof(GeneratedEndpoints.MinimalApiGenerator).Assembly.GetName().Version?.ToString() ?? "";

    internal const string FileHeader =
        "//-----------------------------------------------------------------------------\n" +
        "// <auto-generated>\n" +
        "// This code was generated by MinimalApiGenerator which can be found\n" +
        "// in the GeneratedEndpoints namespace.\n" +
        "//\n" +
        "// Changes to this file may cause incorrect behavior\n" +
        "// and will be lost if the code is regenerated.\n" +
        "// </auto-generated>\n" +
        "//-----------------------------------------------------------------------------\n" +
        "\n" +
        "#nullable enable";

    internal static string GeneratedTypeAttributes =>
        $"""
         [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{GeneratorName}", "{GeneratorVersion}")]
         [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
         """;

    internal const string FallbackHttpMethod = "__FALLBACK__";

    internal const string NameAttributeNamedParameter = "Name";
    internal const string IsOptionalAttributeNamedParameter = "IsOptional";
    internal const string PolicyNameAttributeNamedParameter = "PolicyName";
    internal const string EmptyBodyBehaviorAttributeNamedParameter = "EmptyBodyBehavior";

    internal const string RoutingNamespace = $"{BaseNamespace}.Routing";

    internal const string AddEndpointHandlersClassName = "EndpointServicesExtensions";
    internal const string AddEndpointHandlersMethodName = "AddEndpointHandlers";
    internal const string AddEndpointHandlersMethodHint = $"{AddEndpointHandlersMethodFullyQualifiedName}.g.cs";

    internal const string UseEndpointHandlersClassName = "EndpointRouteBuilderExtensions";
    internal const string UseEndpointHandlersMethodName = "MapEndpointHandlers";
    internal const string UseEndpointHandlersMethodHint = $"{UseEndpointHandlersMethodFullyQualifiedName}.g.cs";

    internal const string ConfigureMethodName = "Configure";
    internal const string AsyncSuffix = "Async";
    internal const string ApplicationJsonContentType = "application/json";
    internal const string GlobalPrefix = "global::";

    private const string BaseNamespace = "Microsoft.AspNetCore.Generated";
    internal const string AttributesNamespace = $"{BaseNamespace}.Attributes";
    private const string AddEndpointHandlersMethodFullyQualifiedName = $"{RoutingNamespace}.{AddEndpointHandlersMethodName}";
    private const string UseEndpointHandlersMethodFullyQualifiedName = $"{RoutingNamespace}.{UseEndpointHandlersMethodName}";
}
